//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINY.Web.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class vItem
    {
        public int ItemId { get; set; }
        public int AuthorId { get; set; }
        public int WallId { get; set; }
        public int NbCol { get; set; }
        public string Note { get; set; }
        public string PicturePath { get; set; }
        public string Url { get; set; }
        public string VideoPath { get; set; }
    }
}
