//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miny.Reader.ViewModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinyReaderContext : DbContext
    {
        public MinyReaderContext()
            : base("name=MinyReaderConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vItemDetail> vItemDetails { get; set; }
        public DbSet<vItemNote> vItemNotes { get; set; }
        public DbSet<vItemPicture> vItemPictures { get; set; }
        public DbSet<vItemUrl> vItemUrls { get; set; }
    }
}
