//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miny.Reader.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vItemPicture
    {
        public int ItemId { get; set; }
        public string PicturePath { get; set; }
    }
}
